akademik/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dosen', 'DosenController');

Route::resource('fakultas', 'FakultasController');

Route::resource('jurusan', 'JurusanController');

Route::resource('kelas', 'KelasController');

Route::resource('mahasiswa', 'MahasiswaController');

Route::resource('matkulr', 'MatkulrController');

Route::resource('profile', 'ProfileController');

Route::resource('rencana', 'RencanaController');

Route::resource('transkrip', 'TranskripController');

Route::resource('tu', 'TuController');

Route::get('/listmahasiswa', 'MahasiswaController@showPdf');

Route::get('/listjurusan', 'JurusanController@showPdf');

Route::get('/listfakultas', 'FakultasController@showPdf');

Route::get('/listdosen', 'DosenController@showPdf');

Route::get('/listtu', 'TuController@showPdf');

Route::get('/listkelas', 'KelasController@showPdf');

Route::get('/transkripmahasiswa', 'TranskripController@showPdf');

Route::get('/rencanastudi/{rencana}', 'RencanaController@showPdf')->name('rencana.rencanastudi');

Route::get('/mahasiswaexport', 'MahasiswaController@exportExcel');

Route::get('/jurusanexport', 'JurusanController@exportExcel');

Route::get('/fakultasexport', 'FakultasController@exportExcel');

Route::get('/dosenexport', 'DosenController@exportExcel');

Route::get('/tuexport', 'TuController@exportExcel');

Route::get('/kelasexport', 'KelasController@exportExcel');

akademik/app/Fakultas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fakultas extends Model
{
	protected $table = 'fakultas';

	protected $guarded = [];

    public function getJurusans(){
    	return $this->hasMany('App\Jurusan', 'fakultas_id');
    }
}

akademik/app/Http/Controllers/FakultasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Fakultas;
use Illuminate\Support\Facades\Auth;
use App\Exports\ExportFakultas;
use Maatwebsite\Excel\Facades\Excel;
use PDF;
use Alert;

class FakultasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Fakultas::all();
        return view('fakultas.index', compact('data'));
    }

    public function create()
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Admin' 
        ){
            return view('fakultas.form');
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Admin' 
        ){
            $request->validate([
                "nama_fakultas" => 'required|unique:fakultas'
            ]);
            $data = Fakultas::create([
                "nama_fakultas" => $request['nama_fakultas']
            ]);

            Alert::success('Berhasil', 'Fakultas berhasil disimpan');
            return redirect(route('fakultas.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function show($id)
    {
        $data = Fakultas::find($id);
        return view('fakultas.detail', compact('data'));
    }

    public function edit($id)
    {   
        $user = Auth::user();
        if(
            $user->getProfile->status=='Admin' 
        ){
            $data = Fakultas::find($id);
        
            return view('fakultas.form_edit',compact('data'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function update(Request $request, $id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Admin' 
        ){
            $request->validate([
                "nama_fakultas" => 'required'
            ]);
            $data = Fakultas::find($id)->update([
                "nama_fakultas" => $request['nama_fakultas']
            ]);

            Alert::success('Berhasil', 'Fakultas berhasil diperbarui');
            return redirect(route('fakultas.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function destroy($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Admin' 
        ){
            $data = Fakultas::destroy($id);

            Alert::success('Berhasil', 'Fakultas berhasil dihapus');
            return redirect(route('fakultas.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function showPdf(){
        $data = Fakultas::all();
        // dd($data);
        $pdf = PDF::loadView('fakultas.list_fakultas', [
            'data' => $data
        ]);

        return $pdf->stream('List_Fakultas.pdf');
    }

    public function exportExcel() 
    {
        return Excel::download(new ExportFakultas, 'fakultas.xlsx');
    }
}

akademik/resources/views/fakultas/detail.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'Detail')

@section ('content')

<section class="content">
  <div class="card">
    <div class="card-header">
    <div class="card-body mt-2">
      <table class="table table-bordered">
        <tr>
          <td>Id</td>
          <td>{{$data->id}}</td>
        </tr>
        <tr>
          <td>Nama Fakultas</td>
          <td>{{$data->nama_fakultas}}</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="pl-3 my-2">
    <a href="{{route('fakultas.index')}}"><button type="button" class="btn btn-warning">Back to Index</button></a>
  </div>
</section>


@endsection

akademik/resources/views/fakultas/form.blade.php
@extends ('layout.master')

@section ('title', 'Create Fakultas')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('fakultas.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('fakultas.store')}}" method="Post">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama_fakultas">Nama Fakultas</label>
                    <input type="text" class="form-control" id="nama_fakultas" name="nama_fakultas" placeholder="Masukkan Nama Fakultas" value="{{old('title', '')}}">
                    @error('nama_fakultas')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/fakultas/form_edit.blade.php
@extends ('layout.master')

@section ('title', 'Edit Fakultas')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('fakultas.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('fakultas.update',['fakulta' => $data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama_fakultas">Nama Fakultas</label>
                    <input type="text" class="form-control" id="nama_fakultas" name="nama_fakultas" placeholder="Masukkan Nama Fakultas" value="{{old('title', $data->nama_fakultas)}}">
                    @error('nama_fakultas')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/fakultas/index.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'List Fakultas')

@section ('content')

<section class="content">
	@if(session('success'))
		<div class="alert alert-success">
			{{session('success')}}
		</div>
	@endif
  <div class="card">
    <div class="card-header">
    <h3 class="card-title">Tabel Fakultas</h3>
    <div class="card-tools">
     	<button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="pl-3 my-2">
       @if (Auth::user()->getProfile)
        @if (Auth::user()->getProfile->status == 'Admin')
         <a href="{{route('fakultas.create')}}"><button type="button" class="btn btn-primary">Create</button></a>
        @endif
      @endif
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>                  
          <tr>
            <th style="width: 10px">#</th>
            <th>Nama Fakultas</th>
            <th style="width: 160px">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($data as $key => $value)
          <tr>
            <td>{{$key+1}}</td>
            <td>{{$value->nama_fakultas}}</td>
            <td>
            	<div >
	            	<a href="{{route('fakultas.show', ['fakulta' => $value->id])}}"><button class="btn btn-default" title="Detail"><i class="fa fa-search-plus" aria-hidden="true"></i></button></a>
                @if (Auth::user()->getProfile)
                    @if (Auth::user()->getProfile->status == 'Admin')
                      <a href="{{route('fakultas.edit', ['fakulta'=> $value->id])}}"><button class="btn btn-default" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
                      <form role="form" action="{{route('fakultas.destroy', ['fakulta'=>$value->id])}}" method="POST" style="display:inline">
                        @csrf
                        @method('DELETE')
                        <a href=# ><button class="btn btn-default" type="submit" title="Delete"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
                        </form>
                  @endif
                @endif
            	</div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    <div class="pl-3 my-2">
      <a href="{{'/listfakultas'}}"><button type="button" class="btn btn-primary">Download List Fakultas</button></a>
      <a href="{{'/fakultasexport'}}"><button type="button" class="btn btn-primary">Download List Fakultas</button></a>
    </div>
  </div>
</section>


@endsection

akademik/resources/views/fakultas/list_fakultas.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SIM AKADEMIK</title>
</head>
<body>
  <section class="content">
  <div class="card">
    <div class="card-header">
    <h3 class="card-title">Tabel Fakultas</h3>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>                  
          <tr>
            <th style="width: 10px">#</th>
            <th>Nama Fakultas</th>
          </tr>
        </thead>
        <tbody>
          @foreach($data as $key => $value)
          <tr>
            <td>{{$key+1}}</td>
            <td>{{$value->nama_fakultas}}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</section>
</body>
</html>