akademik/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dosen', 'DosenController');

Route::resource('fakultas', 'FakultasController');

Route::resource('jurusan', 'JurusanController');

Route::resource('kelas', 'KelasController');

Route::resource('mahasiswa', 'MahasiswaController');

Route::resource('matkulr', 'MatkulrController');

Route::resource('profile', 'ProfileController');

Route::resource('rencana', 'RencanaController');

Route::resource('transkrip', 'TranskripController');

Route::resource('tu', 'TuController');

Route::get('/listmahasiswa', 'MahasiswaController@showPdf');

Route::get('/listjurusan', 'JurusanController@showPdf');

Route::get('/listfakultas', 'FakultasController@showPdf');

Route::get('/listdosen', 'DosenController@showPdf');

Route::get('/listtu', 'TuController@showPdf');

Route::get('/listkelas', 'KelasController@showPdf');

Route::get('/transkripmahasiswa', 'TranskripController@showPdf');

Route::get('/rencanastudi/{rencana}', 'RencanaController@showPdf')->name('rencana.rencanastudi');

Route::get('/mahasiswaexport', 'MahasiswaController@exportExcel');

Route::get('/jurusanexport', 'JurusanController@exportExcel');

Route::get('/fakultasexport', 'FakultasController@exportExcel');

Route::get('/dosenexport', 'DosenController@exportExcel');

Route::get('/tuexport', 'TuController@exportExcel');

Route::get('/kelasexport', 'KelasController@exportExcel');

akademik/app/Jurusan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jurusan extends Model
{
	protected $table = 'jurusans';

    protected $guarded = [];

    public function getFakultas(){
    	return $this->belongsTo('App\Fakultas', 'fakultas_id');
    }

    public function getMahasiswas(){
    	return $this->hasMany('App\Mahasiswa', 'jurusan_id');
    }

    public function getDosens(){
    	return $this->hasMany('App\Dosen', 'jurusan_id');
    }

    public function getTus(){
    	return $this->hasMany('App\Tu', 'jurusan_id');
    }

    public function getKelas(){
    	return $this->hasMany('App\Kelas', 'jurusan_id');
    }
}

akademik/app/Http/Controllers/JurusanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Exports\ExportJurusan;
use Maatwebsite\Excel\Facades\Excel;
use App\Jurusan;
use App\Fakultas;
use PDF;
use Alert;

class JurusanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Jurusan::all();
        return view('jurusan.index', compact('data'));
    }

    public function create()
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Tu' ||
            $user->getProfile->status=='Admin'
        ){
            $fakultas = Fakultas::all();
            return view('jurusan.form',[
                'fakultas' => $fakultas
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function store(Request $request)
    {   
        $user = Auth::user();
        if(
            $user->getProfile->status=='Tu' ||
            $user->getProfile->status=='Admin'
        ){
            $request->validate([
                "nama_jurusan" => 'required|unique:jurusans',
                "fakultas_id"    => 'required'
            ]);
            $data = Jurusan::create([
                "nama_jurusan" => $request['nama_jurusan'],
                "fakultas_id"    => $request['fakultas_id']
            ]);

            Alert::success('Berhasil', 'Jurusan berhasil disimpan');
            return redirect(route('jurusan.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function show($id)
    {
        $data = Jurusan::find($id);
        return view('jurusan.detail', compact('data'));
    }

    public function edit($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Tu' ||
            $user->getProfile->status=='Admin'
        ){
            $data = Jurusan::find($id);
            $fakultas = Fakultas::all();
            return view('jurusan.form_edit',[
                'data' => $data,
                'fakultas' => $fakultas
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function update(Request $request, $id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Tu' ||
            $user->getProfile->status=='Admin'
        ){
            $request->validate([
                "nama_jurusan" => 'required',
                "fakultas_id"    => 'required'
            ]);
            $data = Jurusan::find($id)->update([
                "nama_jurusan" => $request['nama_jurusan'],
                "fakultas_id"    => $request['fakultas_id']
            ]);

            Alert::success('Berhasil', 'Jurusan berhasil diperbarui');
            return redirect(route('jurusan.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function destroy($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Tu' ||
            $user->getProfile->status=='Admin'
        ){
            $data = Jurusan::destroy($id);

            Alert::success('Berhasil', 'Jurusan berhasil dihapus');
            return redirect(route('jurusan.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function showPdf(){
        $data = Jurusan::all();
        // dd($data);
        $pdf = PDF::loadView('jurusan.list_jurusan', [
            'data' => $data
        ]);

        return $pdf->stream('List_Jurusan.pdf');
    }

    public function exportExcel() 
    {
        return Excel::download(new ExportJurusan, 'jurusan.xlsx');
    }
}

akademik/resources/views/jurusan/detail.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'Detail')

@section ('content')

<section class="content">
  <div class="card">
    <div class="card-header">
    <div class="card-body mt-2">
      <table class="table table-bordered">
        <tr>
          <td>Id</td>
          <td>{{$data->id}}</td>
        </tr>
        <tr>
          <td>Nama Jurusan</td>
          <td>{{$data->nama_jurusan}}</td>
        </tr>
        <tr>
          <td>Nama Fakultas</td>
          <td>{{$data->getFakultas->nama_fakultas}}</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="pl-3 my-2">
    <a href="{{route('jurusan.index')}}"><button type="button" class="btn btn-warning">Back to Index</button></a>
  </div>
</section>


@endsection

akademik/resources/views/jurusan/form.blade.php
@extends ('layout.master')

@section ('title', 'Create Jurusan')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('jurusan.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('jurusan.store')}}" method="Post">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama_jurusan">Nama Jurusan</label>
                    <input type="text" class="form-control" id="nama_jurusan" name="nama_jurusan" placeholder="Masukkan Nama Jurusan" value="{{old('title', '')}}">
                    @error('nama_jurusan')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="fakultas_id">Nama Fakultas</label>
                    <select id="fakultas_id" name="fakultas_id">
                      @foreach($fakultas as $key => $value)
                        <option value="{{$value->id}}">{{$value->id}} - {{$value->nama_fakultas}}</option>
                      @endforeach
                    </select>
                    @error('fakultas_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/jurusan/form_edit.blade.php
@extends ('layout.master')

@section ('title', 'Edit Jurusan')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('jurusan.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('jurusan.update',['jurusan' => $data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama_jurusan">Nama Jurusan</label>
                    <input type="text" class="form-control" id="nama_jurusan" name="nama_jurusan" placeholder="Masukkan Nama Jurusan" value="{{old('title', $data->nama_jurusan)}}">
                    @error('nama_jurusan')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="fakultas_id">Nama Fakultas</label>
                    <select id="fakultas_id" name="fakultas_id">
                      @foreach($fakultas as $key => $value)
                        <option value="{{$value->id}}">{{$value->id}} - {{$value->nama_fakultas}}</option>
                      @endforeach
                    </select>
                    @error('fakultas_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/jurusan/index.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'List Jurusan')

@section ('content')

<section class="content">
	@if(session('success'))
		<div class="alert alert-success">
			{{session('success')}}
		</div>
	@endif
  <div class="card">
    <div class="card-header">
    <h3 class="card-title">Tabel Jurusan</h3>
    <div class="card-tools">
     	<button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="pl-3 my-2">
      @if (Auth::user()->getProfile)
        @if (Auth::user()->getProfile->status == "Admin")
         <a href="{{route('jurusan.create')}}"><button type="button" class="btn btn-primary">Create</button></a>
        @endif
      @endif
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>                  
          <tr>
            <th style="width: 10px">#</th>
            <th>Nama Jurusan</th>
            <th>Nama Fakultas</th>
            <th style="width: 160px">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($data as $key => $value)
          <tr>
            <td>{{$key+1}}</td>
            <td>{{$value->nama_jurusan}}</td>
            <td>{{$value->getFakultas->nama_fakultas}}</td>
            <td>
            	<div >
	            	<a href="{{route('jurusan.show', ['jurusan' => $value->id])}}"><button class="btn btn-default" title="Detail"><i class="fa fa-search-plus" aria-hidden="true"></i></button></a>
                @if (Auth::user()->getProfile)
                    @if (Auth::user()->getProfile->status == 'Admin')
                      <a href="{{route('jurusan.edit', ['jurusan'=> $value->id])}}"><button class="btn btn-default" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
                      <form role="form" action="{{route('jurusan.destroy', ['jurusan'=>$value->id])}}" method="POST" style="display:inline">
                        @csrf
                        @method('DELETE')
                        <a href=# ><button class="btn btn-default" type="submit" title="Delete"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
                      </form>
                  @endif
                @endif
            	</div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    <div class="pl-3 my-2">
      <a href="{{'/listjurusan'}}"><button type="button" class="btn btn-primary">Download List Jurusan</button></a>
      <a href="{{'/jurusanexport'}}"><button type="button" class="btn btn-primary">Download List Jurusan</button></a>
    </div>
  </div>
</section>


@endsection

akademik/resources/views/jurusan/list_jurusan.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SIM AKADEMIK</title>
</head>
<body>
  <section class="content">
    @if(session('success'))
      <div class="alert alert-success">
        {{session('success')}}
      </div>
    @endif
    <div class="card">
      <div class="card-header">
      <h3 class="card-title">Tabel Jurusan</h3>
      <div class="card-body">
        <table class="table table-bordered">
          <thead>                  
            <tr>
              <th style="width: 10px">#</th>
              <th>Nama Jurusan</th>
              <th>Nama Fakultas</th>
            </tr>
          </thead>
          <tbody>
            @foreach($data as $key => $value)
            <tr>
              <td>{{$key+1}}</td>
              <td>{{$value->nama_jurusan}}</td>
              <td>{{$value->getFakultas->nama_fakultas}}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </section>
</body>
</html>