akademik/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dosen', 'DosenController');

Route::resource('fakultas', 'FakultasController');

Route::resource('jurusan', 'JurusanController');

Route::resource('kelas', 'KelasController');

Route::resource('mahasiswa', 'MahasiswaController');

Route::resource('matkulr', 'MatkulrController');

Route::resource('profile', 'ProfileController');

Route::resource('rencana', 'RencanaController');

Route::resource('transkrip', 'TranskripController');

Route::resource('tu', 'TuController');

Route::get('/listmahasiswa', 'MahasiswaController@showPdf');

Route::get('/listjurusan', 'JurusanController@showPdf');

Route::get('/listfakultas', 'FakultasController@showPdf');

Route::get('/listdosen', 'DosenController@showPdf');

Route::get('/listtu', 'TuController@showPdf');

Route::get('/listkelas', 'KelasController@showPdf');

Route::get('/transkripmahasiswa', 'TranskripController@showPdf');

Route::get('/rencanastudi/{rencana}', 'RencanaController@showPdf')->name('rencana.rencanastudi');

Route::get('/mahasiswaexport', 'MahasiswaController@exportExcel');

Route::get('/jurusanexport', 'JurusanController@exportExcel');

Route::get('/fakultasexport', 'FakultasController@exportExcel');

Route::get('/dosenexport', 'DosenController@exportExcel');

Route::get('/tuexport', 'TuController@exportExcel');

Route::get('/kelasexport', 'KelasController@exportExcel');

akademik/app/Rencana.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rencana extends Model
{
	protected $table = 'rencanas';

	protected $guarded = [];

    public function getMahasiswa(){
    	return $this->belongsTo('App\Mahasiswa','mahasiswa_id');
    }

    public function getMatkulr(){
    	return $this->hasMany('App\Matkulr','rencana_studi_id');
    }
}

akademik/app/Http/Controllers/RencanaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Mahasiswa;
use App\Rencana;
use App\Matkulr;
use PDF;
use Alert;

class RencanaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'||
            $user->getProfile->status=='Admin' ||
            $user->getProfile->status=='Dosen' ||
            $user->getProfile->status=='Tu'
        ){
            if($user->getProfile->status=='Mahasiswa'){
                $data = Rencana::select('rencanas.*')->leftJoin('mahasiswas','mahasiswas.id','=','rencanas.mahasiswa_id')->where('mahasiswas.profile_id','=',$user->getProfile->id)->get();
            } else if ($user->getProfile->status=='Dosen'){
                $data = Rencana::select('rencanas.*')->leftJoin('mahasiswas','mahasiswas.id','=','rencanas.mahasiswa_id')->leftJoin('dosens','mahasiswas.wali_id','=','dosens.id')->where('dosens.profile_id','=',$user->getProfile->id)->get();
            } else if ($user->getProfile->status=='Tu'){
                $data = Rencana::select('rencanas.*')->leftJoin('mahasiswas','mahasiswas.id','=','rencanas.mahasiswa_id')->where('rencanas.status','=','Approved')->get();
            } else {
                $data = Rencana::select('rencanas.*')->leftJoin('mahasiswas','mahasiswas.id','=','rencanas.mahasiswa_id')->get();
            }
            
            return view('rencana.index', compact('data'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        } 
    }

    public function create()
    {

        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $mahasiswa = Mahasiswa::where('profile_id','=',$user->getProfile->id)->get();
            $tahun = date('Y');
            if(intval(date('m')) < 8){
                $ta = intval($tahun)-1;
                $ta = $ta.'-2';
            } else {
                $ta = intval($tahun).'-1';
            }
            // dd($tahun);
            return view('rencana.form',[
                'mahasiswa' => $mahasiswa,
                'ta'        => $ta
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $request->validate([
                "mahasiswa_id" => 'required',
                "tahun_ajaran"    => 'required|unique_with:rencanas,mahasiswa_id'
            ]);
            $data = Rencana::create([
                "mahasiswa_id"  => $request['mahasiswa_id'],
                "tahun_ajaran"  => $request['tahun_ajaran'],
                "komentar"      => $request['komentar'],
                "status"        => $request['status']
            ]);

            Alert::success('Berhasil', 'Rencana Studi berhasil disimpan');
            return redirect(route('matkulr.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function show($id)
    {   
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'||
            $user->getProfile->status=='Admin' ||
            $user->getProfile->status=='Dosen' ||
            $user->getProfile->status=='Tu'
        ){
            $data = Rencana::find($id);
            $matkuls = Matkulr::where('matkulrs.rencana_studi_id','=',$id)->get();
            return view('rencana.detail', [
                'data'      => $data,
                'matkuls'    => $matkuls
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function edit($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'||
            $user->getProfile->status=='Dosen' ||
            $user->getProfile->status=='Tu'
        ){
            $tahun = date('Y');
            if(intval(date('m')) < 8){
                $ta = intval($tahun)-1;
                $ta = $ta.'-2';
            } else {
                $ta = intval($tahun).'-1';
            }
            $data = Rencana::find($id);
            return view('rencana.form_edit',[
                'data' => $data,
                'ta'    => $ta
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function update(Request $request, $id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'||
            $user->getProfile->status=='Dosen' ||
            $user->getProfile->status=='Tu'
        ){
            $request->validate([
                "mahasiswa_id" => 'required'
            ]);
            $data = Rencana::find($id)->update([
                "komentar"      => $request['komentar'],
                "status"        => $request['status']
            ]);

            Alert::success('Berhasil', 'Rencana Studi berhasil diperbarui');

            if($user->getProfile->status=='Mahasiswa'){
                return redirect(route('matkulr.index'));
            } else {
                return redirect(route('rencana.index'));
            }
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function destroy($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $data = Rencana::destroy($id);

            Alert::success('Berhasil', 'Rencana Studi berhasil dihapus');
            return redirect(route('rencana.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function showPdf($id){
        $user = Auth::user();
        if(
            $user->getProfile->status
        ){
            $data = Rencana::find($id);
            $matkuls = Matkulr::where('matkulrs.rencana_studi_id','=',$id)->get();
            // dd($data);
            $pdf = PDF::loadView('rencana.kartu_rencana_studi', [
                'data' => $data,
                'matkuls'    => $matkuls
            ]);

            return $pdf->stream('Kartu_Rencana_Studi.pdf');
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }
}

akademik/resources/views/rencana/detail.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'Detail')

@section ('content')

<section class="content">
  <div class="card">
    <div class="card-header">
    <div class="card-body mt-2">
      <table class="table table-bordered">
        <tr>
          <td>Id</td>
          <td>{{$data->id}}</td>
        </tr>
        <tr>
          <td>Nama Mahasiswa</td>
          <td>{{$data->getMahasiswa->getProfile->nama_lengkap}}</td>
        </tr>
        <tr>
          <td>NIM</td>
          <td>{{$data->getMahasiswa->nim}}</td>
        </tr>
        <tr>
          <td>Tahun Ajaran</td>
          <td>{{$data->tahun_ajaran}}</td>
        </tr>
        <tr>
          <td>Komentar</td>
          <td>{{$data->komentar}}</td>
        </tr>
        <tr>
          <td>Matakuliah Yang Diambil</td>
          <td>
            <ul>
              @foreach($matkuls as $matkul)
                <li>
                  {{$matkul->getKelas->mata_kuliah}}
                </li>
              @endforeach
            </ul>
          </td>
        </tr>
        <tr>
          <td>Status</td>
          <td>{{$data->status}}</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="pl-3 my-2">
    <a href="{{route('rencana.index')}}"><button type="button" class="btn btn-warning">Back to Index</button></a>
    <a href="{{route('rencana.rencanastudi', ['rencana'=> $data->id])}}"><button type="button" class="btn btn-primary">Download Kartu Rencana Studi Mahasiswa</button></a>
  </div>
</section>


@endsection

akademik/resources/views/rencana/form.blade.php
@extends ('layout.master')

@section ('title', 'Create Rencana Studi')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('rencana.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('rencana.store')}}" method="Post">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="mahasiswa_id">Nama Mahasiswa</label>
                    <select id="mahasiswa_id" name="mahasiswa_id">
                      @foreach($mahasiswa as $key => $value)
                        <option value="{{$value->id}}">{{$value->nim}} - {{$value->getProfile->nama_lengkap}}</option>
                      @endforeach
                    </select>
                    @error('mahasiswa_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="tahun_ajaran">Tahun Ajaran</label>
                    <input type="text" class="form-control" disabled="true" value="{{$ta}}">
                    <input type="hidden" class="form-control" id="tahun_ajaran" name="tahun_ajaran" value="{{$ta}}">
                    @error('tahun_ajaran')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="komentar">Komentar</label>
                    <input type="text" class="form-control" id="komentar" name="komentar" placeholder="Masukkan Komentar" value="{{old('title', '')}}">
                    @error('komentar')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <input type="hidden" class="form-control" id="status" name="status" value="Submitted">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Pilih Mata Kuliah</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/rencana/form_edit.blade.php
@extends ('layout.master')

@section ('title', 'Edit Rencana Studi')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('rencana.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('rencana.update',['rencana' => $data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="mahasiswa_id">Nama Mahasiswa</label>
                    <select id="mahasiswa_id" name="mahasiswa_id" disabled="true">
                        <option value="{{$data->mahasiswa_id}}">{{$data->getMahasiswa->nim}} - {{$data->getMahasiswa->getProfile->nama_lengkap}}</option>
                    </select>
                    <input type="hidden" class="form-control" id="mahasiswa_id" name="mahasiswa_id" value="{{$data->mahasiswa_id}}">
                    @error('mahasiswa_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="tahun_ajaran">Tahun Ajaran</label>
                    <input type="text" class="form-control" disabled="true" value="{{$ta}}">
                    <input type="hidden" class="form-control" id="tahun_ajaran" name="tahun_ajaran" value="{{$ta}}">
                    @error('tahun_ajaran')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="komentar">Komentar</label>
                    <input type="text" class="form-control" id="komentar" name="komentar" placeholder="Masukkan Komentar" value="{{old('title', $data->komentar)}}">
                    @error('komentar')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    @if(Auth::user()->getProfile->status == 'Mahasiswa')
                      <input type="hidden" class="form-control" id="status" name="status" value="Submitted">
                    @elseif(Auth::user()->getProfile->status == 'Dosen')
                      <select id="status" name="status">
                        <option value="Approved">Disetujui</option>
                        <option value="Rejected">Ditolak</option>
                      </select>
                    @elseif(Auth::user()->getProfile->status == 'Tu')
                      <select id="status" name="status">
                        <option value="Approved Final">Disetujui Program Studi</option>
                        <option value="Rejected">Ditolak</option>
                      </select>
                    @endif
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">
                    @if(Auth::user()->getProfile->status == 'Mahasiswa')
                      Pilih Mata Kuliah
                    @else
                      Submit
                    @endif
                  </button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/rencana/index.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'List Rencana Studi')

@section ('content')

<section class="content">
	@if(session('success'))
		<div class="alert alert-success">
			{{session('success')}}
		</div>
	@endif
  <div class="card">
    <div class="card-header">
    <h3 class="card-title">Tabel Rencana Studi</h3>
    <div class="card-tools">
     	<button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="pl-3 my-2">
      @if (Auth::user()->getProfile)
        @if (Auth::user()->getProfile->status == 'Mahasiswa')
    	<a href="{{route('rencana.create')}}"><button type="button" class="btn btn-primary">Create</button></a>
      @endif
      @endif
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>                  
          <tr>
            <th style="width: 10px">#</th>
            <th>Mahasiswa</th>
            <th>Tahun Ajaran</th>
            <th>Status</th>
            <th style="width: 160px">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($data as $key => $value)
          <tr>
            <td>{{$key+1}}</td>
            <td>{{$value->getMahasiswa->nim}}  {{$value->getMahasiswa->getProfile->nama_lengkap}}</td>
            <td>{{$value->tahun_ajaran}}</td>
            <td>{{$value->status}}</td>
            <td>
            	<div >
	            	<a href="{{route('rencana.show', ['rencana' => $value->id])}}"><button class="btn btn-default" title="Detail"><i class="fa fa-search-plus" aria-hidden="true"></i></button></a>
                @if (Auth::user()->getProfile)
                  @if (Auth::user()->getProfile->status == 'Dosen'||(Auth::user()->getProfile->status == 'Mahasiswa' && ($value->status == 'Submitted' || $value->status == 'Rejected') )||Auth::user()->getProfile->status == 'Tu')
	            	  <a href="{{route('rencana.edit', ['rencana'=> $value->id])}}"><button class="btn btn-default" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
                  @endif
                @endif
					<form role="form" action="{{route('rencana.destroy', ['rencana'=>$value->id])}}" method="POST" style="display:inline">
				        @csrf
				        @method('DELETE')
                @if (Auth::user()->getProfile)
                  @if ((Auth::user()->getProfile->status == 'Mahasiswa' && ($value->status == 'Submitted' || $value->status == 'Rejected') )||Auth::user()->getProfile->status == 'Tu')
				        <a href=# ><button class="btn btn-default" type="submit" title="Delete"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
                  @endif
                @endif
				    </form>
            	</div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</section>


@endsection

akademik/resources/views/rencana/kartu_rencana_studi.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SIM AKADEMIK</title>
</head>
<body>
  <section class="content">
    <div class="card">
      <div class="card-header">
      <div class="card-body mt-2">
        <table class="table table-bordered">
          <tr>
            <td>Id</td>
            <td>{{$data->id}}</td>
          </tr>
          <tr>
            <td>Nama Mahasiswa</td>
            <td>{{$data->getMahasiswa->getProfile->nama_lengkap}}</td>
          </tr>
          <tr>
            <td>NIM</td>
            <td>{{$data->getMahasiswa->nim}}</td>
          </tr>
          <tr>
            <td>Tahun Ajaran</td>
            <td>{{$data->tahun_ajaran}}</td>
          </tr>
          <tr>
            <td>Komentar</td>
            <td>{{$data->komentar}}</td>
          </tr>
          <tr>
            <td>Matakuliah Yang Diambil</td>
            <td>
              <ul>
                @foreach($matkuls as $matkul)
                  <li>
                    {{$matkul->getKelas->mata_kuliah}}
                  </li>
                @endforeach
              </ul>
            </td>
          </tr>
          <tr>
            <td>Status</td>
            <td>{{$data->status}}</td>
          </tr>
        </table>
      </div>
    </div>
  </section>
</body>
</html>