akademik/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dosen', 'DosenController');

Route::resource('fakultas', 'FakultasController');

Route::resource('jurusan', 'JurusanController');

Route::resource('kelas', 'KelasController');

Route::resource('mahasiswa', 'MahasiswaController');

Route::resource('matkulr', 'MatkulrController');

Route::resource('profile', 'ProfileController');

Route::resource('rencana', 'RencanaController');

Route::resource('transkrip', 'TranskripController');

Route::resource('tu', 'TuController');

Route::get('/listmahasiswa', 'MahasiswaController@showPdf');

Route::get('/listjurusan', 'JurusanController@showPdf');

Route::get('/listfakultas', 'FakultasController@showPdf');

Route::get('/listdosen', 'DosenController@showPdf');

Route::get('/listtu', 'TuController@showPdf');

Route::get('/listkelas', 'KelasController@showPdf');

Route::get('/transkripmahasiswa', 'TranskripController@showPdf');

Route::get('/rencanastudi/{rencana}', 'RencanaController@showPdf')->name('rencana.rencanastudi');

Route::get('/mahasiswaexport', 'MahasiswaController@exportExcel');

Route::get('/jurusanexport', 'JurusanController@exportExcel');

Route::get('/fakultasexport', 'FakultasController@exportExcel');

Route::get('/dosenexport', 'DosenController@exportExcel');

Route::get('/tuexport', 'TuController@exportExcel');

Route::get('/kelasexport', 'KelasController@exportExcel');

akademik/app/Matkulr.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Matkulr extends Model
{
	protected $table = 'matkulrs';

	protected $guarded = [];

    public function getRencana(){
    	return $this->belongsTo('App\Rencana', 'rencana_studi_id');
    }

    public function getKelas(){
    	return $this->belongsTo('App\Kelas', 'kelas_id');
    }
}

akademik/app/Http/Controllers/MatkulrController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Rencana;
use App\Kelas;
use App\Matkulr;
use Alert;

class MatkulrController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'||
            $user->getProfile->status=='Admin' ||
            $user->getProfile->status=='Tu'
        ){
            if($user->getProfile->status == 'Mahasiswa'){
                $data = Matkulr::select('matkulrs.*')->leftJoin('rencanas','rencanas.id','=','matkulrs.rencana_studi_id')->leftJoin('mahasiswas','rencanas.mahasiswa_id','=','mahasiswas.id')->where('mahasiswas.profile_id','=',$user->getProfile->id)->get();
            } else {
                $data = Matkulr::all();
            }
            $fix = Rencana::select('rencanas.*')->leftJoin('mahasiswas','rencanas.mahasiswa_id','=','mahasiswas.id')->where('mahasiswas.profile_id','=',$user->getProfile->id)->get();
            // dd($fix);
            return view('matkulr.index', [
                'data' => $data,
                'fix'   => $fix['0'] 
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function create()
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $kelas = Kelas::all();
            $rencana = Rencana::select('mahasiswas.*','rencanas.*')->leftJoin('mahasiswas','mahasiswas.id','=','rencanas.mahasiswa_id')->leftJoin('profiles','mahasiswas.profile_id','=','profiles.id')->where('profiles.id','=',$user->getProfile->id)->get();
            return view('matkulr.form',[
                'kelas' => $kelas,
                'rencana' => $rencana
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $request->validate([
                "rencana_studi_id" => 'required',
                "kelas_id"    => 'required|unique_with:matkulrs,rencana_studi_id'
            ]);
            $data = Matkulr::create([
                "rencana_studi_id" => $request['rencana_studi_id'],
                "kelas_id"    => $request['kelas_id']
            ]);


            Alert::success('Berhasil', 'Mata kuliah rencana studi berhasil disimpan');
            return redirect(route('matkulr.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function show($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'||
            $user->getProfile->status=='Admin' ||
            $user->getProfile->status=='Tu'
        ){
            $data = Matkulr::find($id);
            return view('matkulr.detail', compact('data'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function edit($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $data = Matkulr::find($id);
            $kelas = Kelas::select('kelas.*')->leftJoin('matkulrs','kelas.id','=','matkulrs.kelas_id')->where('matkulrs.id','=', NULL)->orWhere('matkulrs.id','=',$id)->get();
            return view('matkulr.form_edit',[
                'data' => $data,
                'kelas' => $kelas
            ]);
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function update(Request $request, $id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $request->validate([
                "rencana_studi_id" => 'required',
                "kelas_id"    => 'required'
            ]);
            $data = Matkulr::find($id)->update([
                "rencana_studi_id" => $request['rencana_studi_id'],
                "kelas_id"    => $request['kelas_id']
            ]);

            Alert::success('Berhasil', 'Mata kuliah rencana studi berhasil diperbarui');
            return redirect(route('matkulr.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }

    public function destroy($id)
    {
        $user = Auth::user();
        if(
            $user->getProfile->status=='Mahasiswa'
        ){
            $data = Matkulr::destroy($id);

            Alert::success('Berhasil', 'Mata kuliah rencana studi berhasil dihapus');
            return redirect(route('matkulr.index'));
        } else {
            Alert::warning('Akses Ditolak', 'Anda tidak memiliki akses ke halaman ini');
            return view('denied');   
        }
    }
}

akademik/resources/views/matkulr/detail.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'Detail')

@section ('content')

<section class="content">
  <div class="card">
    <div class="card-header">
    <div class="card-body mt-2">
      <table class="table table-bordered">
        <tr>
          <td>Id</td>
          <td>{{$data->id}}</td>
        </tr>
        <tr>
          <td>Rencana Studi</td>
          <td>{{$data->getRencana->getMahasiswa->nim}}-{{$data->getRencana->getMahasiswa->getProfile->nama_lengkap}}, TA {{$data->getRencana->tahun_ajaran}}</td>
        </tr>
        <tr>
          <td>Mata kuliah</td>
          <td>{{$data->getKelas->mata_kuliah}}</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="pl-3 my-2">
    <a href="{{route('matkulr.index')}}"><button type="button" class="btn btn-warning">Back to Index</button></a>
  </div>
</section>


@endsection

akademik/resources/views/matkulr/form.blade.php
@extends ('layout.master')

@section ('title', 'Add Matakuliah')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('matkulr.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('matkulr.store')}}" method="Post">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="rencana_studi_id">Rencana Studi</label>
                    <select id="rencana_studi_id" name="rencana_studi_id">
                      @foreach($rencana as $key => $value)
                        <option value="{{$value->id}}">{{$value->getMahasiswa->nim}}-{{$value->getMahasiswa->getProfile->nama_lengkap}}, TA {{$value->tahun_ajaran}}</option>
                      @endforeach
                    </select>
                    @error('rencana_studi_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="kelas_id">Nama Kelas</label>
                    <select id="kelas_id" name="kelas_id">
                      @foreach($kelas as $key => $value)
                        <option value="{{$value->id}}">{{$value->id}} - {{$value->mata_kuliah}}</option>
                      @endforeach
                    </select>
                    @error('kelas_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/matkulr/form_edit.blade.php
@extends ('layout.master')

@section ('title', 'Edit Jurusan')

@section ('content')

<section class="content">
  <div class="pl-3">
    <a href="{{route('matkulr.index')}}"><button type="button" class="btn btn-warning mb-3">Back to Index</button></a>
  </div>
  <div class="card card-primary"> 
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('matkulr.update',['matkulr' => $data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="rencana_studi_id">Rencana Studi</label>
                    <select id="rencana_studi_id" name="rencana_studi_id" disabled="true">
                        <option value="{{$data->rencana_studi_id}}">{{$data->getRencana->getMahasiswa->nim}}-{{$data->getRencana->getMahasiswa->getProfile->nama_lengkap}}, TA {{$data->getRencana->tahun_ajaran}}</option>
                    </select>
                    <input type="hidden" class="form-control" id="rencana_studi_id" name="rencana_studi_id" value="{{$data->rencana_studi_id}}">
                    @error('rencana_studi_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="kelas_id">Nama Kelas</label>
                    <select id="kelas_id" name="kelas_id">
                      @foreach($kelas as $key => $value)
                        <option value="{{$value->id}}">{{$value->id}} - {{$value->mata_kuliah}}</option>
                      @endforeach
                    </select>
                    @error('kelas_id')
                      <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
  </div>
</section>


@endsection

akademik/resources/views/matkulr/index.blade.php
@extends ('layout.master')

@push('css')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section ('title', 'List Matakuliah Diambil')

@section ('content')

<section class="content">
	@if(session('success'))
		<div class="alert alert-success">
			{{session('success')}}
		</div>
	@endif
  <div class="card">
    <div class="card-header">
    <h3 class="card-title">Tabel Matakuliah Diambil</h3>
    <div class="card-tools">
     	<button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="pl-3 my-2">
       @if (Auth::user()->getProfile)
        @if (Auth::user()->getProfile->status == 'Mahasiswa')
    	<a href="{{route('matkulr.create')}}"><button type="button" class="btn btn-primary">Add Mata Kuliah</button></a>
        @endif
        @endif
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>                  
          <tr>
            <th style="width: 10px">#</th>
            <th>Rencana Studi</th>
            <th>Mata kuliah</th>
            <th style="width: 160px">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($data as $key => $value)
          <tr>
            <td>{{$key+1}}</td>
            <td>{{$value->getRencana->getMahasiswa->nim}}-{{$value->getRencana->getMahasiswa->getProfile->nama_lengkap}}, TA {{$value->getRencana->tahun_ajaran}}</td>
            <td>{{$value->getKelas->mata_kuliah}}</td>
            <td>
            	<div >
	            	<a href="{{route('matkulr.show', ['matkulr' => $value->id])}}"><button class="btn btn-default" title="Detail"><i class="fa fa-search-plus" aria-hidden="true"></i></button></a>
                @if (Auth::user()->getProfile)
                  @if (Auth::user()->getProfile->status == 'Mahasiswa')
    	            	<a href="{{route('matkulr.edit', ['matkulr'=> $value->id])}}"><button class="btn btn-default" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></button></a>
          					<form role="form" action="{{route('matkulr.destroy', ['matkulr'=>$value->id])}}" method="POST" style="display:inline">
          				        @csrf
          				        @method('DELETE')
          				        <a href=# ><button class="btn btn-default" type="submit" title="Delete"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
          				    </form>
                  @endif
                @endif
            	</div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    <div class="pl-3 my-2">
      <a href="{{route('rencana.show', ['rencana' => $fix->id])}}"><button type="button" class="btn btn-primary">Submit</button></a>
    </div>
  </div>
</section>


@endsection